# Generated by Django 4.2.1 on 2023-06-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authsystem", "0004_alter_custommodel_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommodel",
            name="phone_number",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
