# Generated by Django 4.2.1 on 2023-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authsystem", "0005_alter_custommodel_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommodel",
            name="username",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
